-- MySQL Script generated by MySQL Workbench
-- Thu Oct  5 15:51:26 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL,
  `nickname` VARCHAR(45) NOT NULL,
  `access_token` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dashboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dashboard` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dashboard_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_dashboard_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`api` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  `selector_json` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`component` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `caption` VARCHAR(45) NOT NULL,
  `props_json` JSON NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`widget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`widget` (
  `id` INT NOT NULL,
  `component_id` INT NOT NULL,
  `api_id` INT NOT NULL,
  `repeat_props` JSON NOT NULL,
  `props_json` JSON NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_widget_API1_idx` (`api_id` ASC),
  INDEX `fk_widget_component1_idx` (`component_id` ASC),
  CONSTRAINT `fk_widget_API1`
    FOREIGN KEY (`api_id`)
    REFERENCES `mydb`.`api` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_widget_component1`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`component` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`widget_pos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`widget_pos` (
  `id` INT NOT NULL,
  `widget_id` INT NOT NULL,
  `dashboard_id` INT NOT NULL,
  `x` INT NOT NULL,
  `y` INT NOT NULL,
  `width` INT NOT NULL,
  `height` INT NOT NULL,
  `resizable` TINYINT NOT NULL,
  `autoposition` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_widget_pos_widget1_idx` (`widget_id` ASC),
  INDEX `fk_widget_pos_dashboard1_idx` (`dashboard_id` ASC),
  CONSTRAINT `fk_widget_pos_widget1`
    FOREIGN KEY (`widget_id`)
    REFERENCES `mydb`.`widget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_widget_pos_dashboard1`
    FOREIGN KEY (`dashboard_id`)
    REFERENCES `mydb`.`dashboard` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favorate_widget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favorate_widget` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `widget_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorate wiget_user1_idx` (`user_id` ASC),
  INDEX `fk_favorate wiget_widget1_idx` (`widget_id` ASC),
  CONSTRAINT `fk_favorate wiget_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorate wiget_widget1`
    FOREIGN KEY (`widget_id`)
    REFERENCES `mydb`.`widget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
